# 先构建好 Hadoop Hive 基础镜像
FROM harbor.xxx.cn/flink/hadoop:2.9.2

# 复制 Flink 1.12 jar 客户端

WORKDIR $FLINK_HOME
COPY flink-1.12.0-jar.tar.gz $FLINK_HOME

RUN set -ex; \
    tar -xf $FLINK_HOME/flink-1.12.0-jar.tar.gz --strip-components=1 -C $FLINK_HOME; \
    rm $FLINK_HOME/flink-1.12.0-jar.tar.gz; \
    chmod 777 $FLINK_HOME/log;


# Configure container
ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 6123 8081
CMD ["help"]