CREATE TABLE `uc_users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `username` varchar(40) DEFAULT NULL COMMENT '用户名',
  `connection_id` bigint(20) DEFAULT NULL COMMENT '废弃',
  `email` varchar(254) CHARACTER SET utf8 DEFAULT NULL COMMENT '邮箱',
  `email_verified` tinyint(1) NOT NULL DEFAULT '0' COMMENT '邮箱是否验证通过',
  `phone_number` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '手机号',
  `phone_number_verified` tinyint(1) NOT NULL DEFAULT '0' COMMENT '手机号是否验证通过',
  `real_name` varchar(40) DEFAULT NULL COMMENT '真实姓名',
  `display_name` varchar(40) CHARACTER SET utf8 DEFAULT NULL COMMENT '展示名称',
  `nickname` varchar(40) DEFAULT NULL COMMENT '昵称',
  `given_name` varchar(40) CHARACTER SET utf8 DEFAULT NULL COMMENT '名',
  `family_name` varchar(40) CHARACTER SET utf8 DEFAULT NULL COMMENT '姓',
  `middle_name` varchar(40) CHARACTER SET utf8 DEFAULT NULL COMMENT 'middle name',
  `avatar_url` varchar(2000) CHARACTER SET utf8 DEFAULT NULL COMMENT '头像',
  `password` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '密码',
  `password_strength` int(11) DEFAULT NULL COMMENT '密码强度',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `locked` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否冻结',
  `type` smallint(6) NOT NULL COMMENT '暂不支持',
  `source` varchar(100) CHARACTER SET utf8 DEFAULT NULL COMMENT '注册渠道',
  `last_login_at` timestamp NULL DEFAULT NULL COMMENT '上次登录时间',
  `gender` varchar(10) CHARACTER SET utf8 DEFAULT NULL COMMENT '性别',
  `birthday` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `zone_info` varchar(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '时区',
  `locale` varchar(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '预留信息',
  `website` varchar(2000) CHARACTER SET utf8 DEFAULT NULL COMMENT '个人主页',
  `address` varchar(1000) CHARACTER SET utf8 DEFAULT NULL COMMENT '地址',
  `extra` varchar(5000) CHARACTER SET utf8 DEFAULT NULL COMMENT '扩展字段',
  `created_at` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `external_source` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '外部来源',
  `external_id` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '外部来源id',
  `reg_client_id` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT 'reg client id',
  `version` int(11) DEFAULT NULL COMMENT '版本',
  `is_delete` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除delete flag (0:not,1:yes)',
  `register_ip` varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '注册IP',
  `invitation_code` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '扩展字段',
  `sign_in_type` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `authorities` varchar(1024) CHARACTER SET utf8 DEFAULT NULL,
  `referrer_id` bigint(20) DEFAULT NULL,
  `channel` varchar(64) DEFAULT NULL,
  `combination` varchar(512) DEFAULT NULL,
  `group` varchar(64) DEFAULT 'default',
  `metadata` varchar(2048) DEFAULT NULL,
  `sign_up_type` varchar(64) DEFAULT NULL,
  `updated_by` varchar(128) DEFAULT NULL,
  `tenant_id` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_username` (`username`) USING BTREE,
  UNIQUE KEY `uk_phone_number` (`phone_number`) USING BTREE,
  UNIQUE KEY `un_uc_users_phone` (`phone_number`,`group`),
  UNIQUE KEY `un_uc_users_username` (`username`,`group`),
  KEY `idx_uc_users_nickname` (`nickname`),
  KEY `idx_uc_users_group` (`group`)
) ENGINE=InnoDB AUTO_INCREMENT=217214 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='用户信息表';




CREATE TABLE `order` (
  `order_id` bigint(20) NOT NULL COMMENT '主键',
  `tenant_id` int(10) NOT NULL COMMENT '租户id',
  `out_id` varchar(32) DEFAULT '' COMMENT '外部订单id',
  `purchase_order_id` bigint(19) NOT NULL COMMENT '购物单id',
  `device_source` varchar(16) DEFAULT NULL COMMENT '来源: IOS/PC...',
  `biz_code` varchar(32) NOT NULL DEFAULT '' COMMENT '业务类型',
  `buyer_id` bigint(19) NOT NULL COMMENT '买家id',
  `buyer_name` varchar(64) NOT NULL DEFAULT '' COMMENT '买家姓名',
  `shop_name` varchar(64) DEFAULT NULL COMMENT '卖家姓名',
  `shop_id` bigint(20) NOT NULL COMMENT '卖家id',
  `enable_status` smallint(5) NOT NULL COMMENT '是否可见, 1: 可见; 0: 不可见',
  `pay_status` varchar(64) NOT NULL,
  `delivery_status` varchar(64) NOT NULL,
  `receive_status` varchar(32) NOT NULL,
  `reverse_status` varchar(64) NOT NULL,
  `pay_at` datetime DEFAULT NULL COMMENT '支付完成时间',
  `shipping_at` datetime DEFAULT NULL COMMENT '发货时间',
  `confirm_at` datetime DEFAULT NULL COMMENT '确认收货时间',
  `paid_amount` bigint(20) NOT NULL COMMENT '实际支付金额',
  `sku_origin_total_amount` bigint(20) NOT NULL,
  `sku_adjust_amount` bigint(20) NOT NULL,
  `sku_discount_total_amount` bigint(20) NOT NULL,
  `ship_fee_origin_amount` bigint(20) NOT NULL,
  `ship_fee_adjust_amount` bigint(20) NOT NULL,
  `ship_fee_discount_total_amount` bigint(20) NOT NULL,
  `tax_fee_origin_amount` bigint(20) NOT NULL,
  `tax_fee_adjust_amount` bigint(20) NOT NULL,
  `tax_fee_discount_total_amount` bigint(20) NOT NULL,
  `discount_detail` varchar(1024) DEFAULT NULL,
  `buyer_notes` varchar(127) DEFAULT NULL COMMENT '买家留言',
  `delivery_address` varchar(1024) DEFAULT NULL COMMENT '收货地址, json格式,包含详细地址和各级id,以及type',
  `shop_notes` varchar(127) DEFAULT NULL COMMENT '卖家留言',
  `tag` bigint(19) DEFAULT NULL COMMENT '打标',
  `extra_json` varchar(1024) DEFAULT NULL COMMENT '拓展字段',
  `version` int(10) NOT NULL COMMENT '乐观锁',
  `updated_by` varchar(64) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `accomplish_at` datetime DEFAULT NULL COMMENT '订单完成时间',
  PRIMARY KEY (`order_id`),
  KEY `idx_order_tenant_id` (`tenant_id`),
  KEY `idx_order_purchase_order_id` (`purchase_order_id`),
  KEY `idx_order_biz_code` (`biz_code`),
  KEY `idx_order_buyer_id` (`buyer_id`),
  KEY `idx_order_shop_id` (`shop_id`),
  KEY `idx_order_out_id` (`out_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='店铺订单';



CREATE TABLE `order_line` (
  `order_line_id` bigint(20) NOT NULL COMMENT '订单行id',
  `tenant_id` int(10) DEFAULT NULL COMMENT '租户id',
  `out_id` varchar(32) DEFAULT NULL COMMENT '外部订单号',
  `biz_code` varchar(32) NOT NULL DEFAULT '' COMMENT '业务类型',
  `purchase_order_id` bigint(20) NOT NULL COMMENT '购物单id',
  `order_id` bigint(20) NOT NULL COMMENT '店铺订单id',
  `buyer_id` bigint(20) NOT NULL COMMENT '买家id',
  `buyer_name` varchar(64) NOT NULL DEFAULT '' COMMENT '买家姓名',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺id',
  `shop_name` varchar(128) DEFAULT '' COMMENT '店铺名称',
  `warehouse_code_plan` varchar(32) DEFAULT NULL COMMENT '计划发货门店id',
  `warehouse_code_actual` varchar(32) DEFAULT NULL COMMENT '实际发货门店id',
  `pay_status` varchar(32) NOT NULL,
  `delivery_status` varchar(32) NOT NULL,
  `receive_status` varchar(32) NOT NULL,
  `reverse_status` varchar(64) NOT NULL,
  `enable_status` smallint(5) NOT NULL COMMENT '是否可见. 1: 可见. 0: 不可见',
  `refund_at` datetime DEFAULT NULL COMMENT '退款完成时间',
  `confirm_at` datetime DEFAULT NULL COMMENT '确认收获时间',
  `sku_id` bigint(19) DEFAULT NULL COMMENT 'sku id',
  `sku_code` varchar(64) DEFAULT NULL COMMENT 'sku code',
  `sku_name` varchar(512) NOT NULL DEFAULT '' COMMENT 'sku 名称',
  `sku_image` varchar(512) DEFAULT '' COMMENT 'sku 缩率图',
  `sku_attr` varchar(1024) DEFAULT NULL COMMENT 'sku 销售属性',
  `quantity` int(10) NOT NULL COMMENT '数量',
  `paid_amount` bigint(20) NOT NULL COMMENT '实际支付金额',
  `sku_origin_total_amount` bigint(20) NOT NULL,
  `sku_adjust_amount` bigint(20) NOT NULL,
  `sku_discount_total_amount` bigint(20) NOT NULL,
  `ship_fee_origin_amount` bigint(20) NOT NULL,
  `ship_fee_adjust_amount` bigint(20) NOT NULL,
  `ship_fee_discount_total_amount` bigint(20) NOT NULL,
  `tax_fee_origin_amount` bigint(20) NOT NULL,
  `tax_fee_adjust_amount` bigint(20) NOT NULL,
  `tax_fee_discount_total_amount` bigint(20) NOT NULL,
  `discount_detail` varchar(2048) DEFAULT NULL,
  `device_source` varchar(16) NOT NULL COMMENT '来源: IOS/PC.....',
  `tag` bigint(19) NOT NULL COMMENT '打标',
  `master_id` bigint(19) DEFAULT NULL COMMENT '组合商品的主商品id, 如果该商品为主商品, 则为null',
  `extra_json` varchar(1024) DEFAULT NULL COMMENT '拓展字段',
  `version` int(10) unsigned NOT NULL COMMENT '乐观锁',
  `updated_by` varchar(32) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `sku_extra` varchar(1024) DEFAULT NULL COMMENT 'sku和item的一些冗余信息, item_id, item_name, outerSkuCode 等',
  `item_id` bigint(20) NOT NULL COMMENT '商品id',
  `item_name` varchar(255) DEFAULT NULL COMMENT '商品名称',
  `sku_line_id` bigint(20) NOT NULL COMMENT '可以近似理解为order按sku维度拆分的Line id',
  `bundle_id` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`order_line_id`),
  KEY `idx_order_line_tenant_id` (`tenant_id`),
  KEY `idx_order_line_biz_code` (`biz_code`),
  KEY `idx_order_line_purchase_order_id` (`purchase_order_id`),
  KEY `idx_order_line_order_id` (`order_id`),
  KEY `idx_order_line_buyer_id` (`buyer_id`),
  KEY `idx_order_line_shop_id` (`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单行';



CREATE TABLE `parana_shop` (
  `id` bigint(20) NOT NULL,
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `outer_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '外部店铺编码',
  `user_id` bigint(20) DEFAULT NULL COMMENT '商家id',
  `user_name` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商家名称',
  `name` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '店铺名称',
  `status` tinyint(1) NOT NULL COMMENT '状态 1:正常, -1:关闭, -2:冻结',
  `type` tinyint(1) NOT NULL COMMENT '店铺类型 1:门店 2:商家 3:出版社',
  `phone` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '联系电话',
  `email` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '电子邮件',
  `image_url` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '店铺图片url',
  `address` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '店铺地址',
  `extra_json` text COLLATE utf8mb4_unicode_ci COMMENT '店铺额外信息,建议json字符串',
  `tags` bigint(20) DEFAULT NULL COMMENT '店铺标签',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '更新时间',
  `updated_by` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新者',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_name` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='店铺表';



CREATE TABLE `parana_item` (
  `id` bigint(20) NOT NULL,
  `extension_type` smallint(6) DEFAULT '0' COMMENT '扩展类型',
  `spu_id` bigint(20) DEFAULT NULL,
  `tenant_id` bigint(20) DEFAULT NULL COMMENT '租户id',
  `category_id` bigint(20) NOT NULL COMMENT '类目id',
  `item_code` varchar(45) DEFAULT NULL COMMENT '商品编码',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺id',
  `shop_name` varchar(128) DEFAULT '' COMMENT '店铺名',
  `brand_id` bigint(20) DEFAULT NULL COMMENT '品牌id',
  `brand_name` varchar(128) DEFAULT NULL COMMENT '品牌名',
  `delivery_fee_temp_id` bigint(20) NOT NULL COMMENT '运费模板id',
  `name` varchar(1024) NOT NULL DEFAULT '' COMMENT '商品名',
  `advertise` mediumtext COMMENT '广告',
  `main_image` varchar(512) NOT NULL DEFAULT '' COMMENT '主图地址',
  `video_url` varchar(512) DEFAULT NULL COMMENT '视频地址',
  `status` smallint(6) NOT NULL COMMENT '商品状态：1(上架),-1(下架),-2(冻结),-3(删除)',
  `type` smallint(6) NOT NULL COMMENT '商品类型',
  `sku_attributes_json` varchar(4096) DEFAULT NULL COMMENT 'sku销售属性集合',
  `other_attributes_json` varchar(4096) DEFAULT NULL COMMENT '其它属性',
  `extra_json` mediumtext COMMENT '其它内容',
  `tags` bigint(20) DEFAULT NULL COMMENT '标签',
  `md5_info` varchar(45) DEFAULT NULL,
  `version` int(10) NOT NULL COMMENT '信息版本号',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '最后更新时间',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新者',
  `high_price` int(11) DEFAULT NULL,
  `low_price` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `fk_item_spu1_idx` (`spu_id`) USING BTREE,
  KEY `idx_parana_item_updated_at` (`updated_at`),
  KEY `idx_parana_item_category_id` (`category_id`) USING BTREE,
  KEY `idx_parana_item_item_code` (`item_code`) USING BTREE,
  KEY `idx_parana_item_shop_id` (`shop_id`) USING BTREE,
  KEY `idx_parana_item_shop_id_create_at_status` (`shop_id`,`created_at`,`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;


CREATE TABLE `parana_sku` (
  `id` bigint(20) unsigned NOT NULL,
  `extension_type` smallint(6) DEFAULT '0' COMMENT '扩展类型',
  `tenant_id` smallint(6) DEFAULT NULL COMMENT '租户id',
  `item_id` bigint(20) NOT NULL COMMENT '商品id',
  `sku_template_id` bigint(20) DEFAULT NULL COMMENT 'sku模板id',
  `sku_code` varchar(40) DEFAULT NULL COMMENT 'SKU 编码 (标准库存单位编码)',
  `barcode` varchar(32) DEFAULT NULL COMMENT '商品条码',
  `shape_code` varchar(128) DEFAULT NULL,
  `outer_id` varchar(40) DEFAULT NULL COMMENT '外部id',
  `shop_id` bigint(20) NOT NULL,
  `name` varchar(1024) DEFAULT NULL COMMENT '名称',
  `image` varchar(1024) DEFAULT NULL COMMENT '图片url',
  `price` int(11) DEFAULT NULL COMMENT '实际售卖价格',
  `status` tinyint(1) NOT NULL COMMENT 'sku状态, 1: 上架, -1:下架, -2:冻结, -3:删除',
  `audit_status` smallint(6) DEFAULT NULL COMMENT '审核状态',
  `type` smallint(6) NOT NULL COMMENT '商品类型',
  `inventory_type` smallint(6) DEFAULT NULL COMMENT '库存类型',
  `sku_ids_json` varchar(512) DEFAULT NULL,
  `price_json` varchar(255) DEFAULT NULL COMMENT 'sku其他各种价格的json表示形式',
  `ios_price_json` varchar(255) DEFAULT NULL COMMENT '渠道iOS价格',
  `attrs_json` varchar(1024) DEFAULT NULL COMMENT 'json存储的sku属性键值对',
  `version` int(10) NOT NULL COMMENT 'sku信息版本',
  `extra_json` text COMMENT 'sku额外信息',
  `tags` bigint(20) DEFAULT NULL COMMENT '标签',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '最后更新时间',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新者',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_item_id` (`item_id`) USING BTREE,
  KEY `idx_parana_sku_updated_at` (`updated_at`),
  KEY `idx_parana_sku_shop_id` (`shop_id`),
  KEY `idx_parana_item_barcode` (`barcode`),
  KEY `idx_parana_sku_sku_code` (`sku_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='商品SKU表';


